image: golang:1.10
before_script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - pwd
  - cp -r /builds/yuichi101 /go/src/github.com/yuichi10/
  - cd /go/src/github.com/yuichi10/matrix
  - dep ensure

build:
  script:
    - go build .

golint:
  script:
    - golint 

test:
  script:
    - go test -cover