image: golang:1.10
stages:
  - build
  - cleanup_build
  - test

before_script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - pwd
  - mkdir -p /go/src/github.com/yuichi10/
  - cp -r /builds/yuichi101/matrix /go/src/github.com/yuichi10/
  - cd /go/src/github.com/yuichi10/matrix
  - dep ensure


build-1.8:
  stage: build
  script:
    - go build .
  image: golang:1.8

build:
  stage: build
  script:
    - go build .

cleanup_build_job:
  stage: cleanup_build
  script:
    - echo "clean up for failed!!!!!!"
  when: on_failure

cleanup_build_job_success:
  stage: cleanup_build
  script:
    - echo "clean up for success!!!!!!"
  when: on_success

golint:
  stage: test
  environment:
    on_stop: test_cover
  before_script: 
    - go get -u golang.org/x/lint/golint
  script:
    - golint 
  after_script:
    - ls

test_manual:
  stage: test
  script:
    - go test -cover
  when: manual

test_cover:
  stage: test
  environment:
    action: stop
  script:
    - go test -cover

test_without_master:
  stage: test
  script:
    - go test -cover 
  except: 
    - master

test_only_master:
  stage: test
  script:
    - go test -cover 
  only: 
    - master
